include_guard(GLOBAL)

function(qiven_resolve_source_dependency)
    set(one_value_args NAME TARGET ROOT_VARIABLE DEFAULT_SIBLING BUILD_SUBDIR TEST_OPTION)
    set(multi_value_args REQUIRED_PATHS)
    cmake_parse_arguments(QSD "" "${one_value_args}" "${multi_value_args}" ${ARGN})
    _qiven_require_clean_parse(QSD "qiven_resolve_source_dependency")

    foreach(required NAME TARGET ROOT_VARIABLE DEFAULT_SIBLING)
        if(NOT QSD_${required})
            message(FATAL_ERROR "qiven_resolve_source_dependency: ${required} is required")
        endif()
    endforeach()
    _qiven_require_variable_name("${QSD_ROOT_VARIABLE}" "qiven_resolve_source_dependency ROOT_VARIABLE")
    if(QSD_TEST_OPTION)
        _qiven_require_variable_name("${QSD_TEST_OPTION}" "qiven_resolve_source_dependency TEST_OPTION")
    endif()
    _qiven_require_safe_relative_path("${QSD_DEFAULT_SIBLING}" "qiven_resolve_source_dependency DEFAULT_SIBLING")

    if(TARGET ${QSD_TARGET})
        return()
    endif()

    if(NOT QSD_BUILD_SUBDIR)
        set(QSD_BUILD_SUBDIR "${QSD_NAME}")
    endif()
    _qiven_require_safe_relative_path("${QSD_BUILD_SUBDIR}" "qiven_resolve_source_dependency BUILD_SUBDIR")
    foreach(relative IN LISTS QSD_REQUIRED_PATHS)
        _qiven_require_safe_relative_path("${relative}" "qiven_resolve_source_dependency REQUIRED_PATHS")
    endforeach()

    if(NOT DEFINED ${QSD_ROOT_VARIABLE})
        set(${QSD_ROOT_VARIABLE} "" CACHE PATH "Path to the ${QSD_NAME} source tree")
    endif()

    if(NOT "${${QSD_ROOT_VARIABLE}}" STREQUAL "")
        set(_candidate_source "${${QSD_ROOT_VARIABLE}}")
    else()
        set(_candidate_source "${CMAKE_CURRENT_SOURCE_DIR}/../${QSD_DEFAULT_SIBLING}")
    endif()
    cmake_path(ABSOLUTE_PATH _candidate_source NORMALIZE OUTPUT_VARIABLE source_dir)

    set(required_paths CMakeLists.txt ${QSD_REQUIRED_PATHS})
    foreach(relative IN LISTS required_paths)
        if(NOT EXISTS "${source_dir}/${relative}")
            message(FATAL_ERROR
                "${QSD_ROOT_VARIABLE} must identify ${QSD_NAME}; missing '${relative}' under '${source_dir}'")
        endif()
    endforeach()

    if(QSD_TEST_OPTION)
        block(SCOPE_FOR VARIABLES)
            set(${QSD_TEST_OPTION} OFF)
            add_subdirectory("${source_dir}" "${CMAKE_CURRENT_BINARY_DIR}/${QSD_BUILD_SUBDIR}" EXCLUDE_FROM_ALL)
        endblock()
    else()
        add_subdirectory("${source_dir}" "${CMAKE_CURRENT_BINARY_DIR}/${QSD_BUILD_SUBDIR}" EXCLUDE_FROM_ALL)
    endif()

    if(NOT TARGET ${QSD_TARGET})
        message(FATAL_ERROR
            "${QSD_NAME} at '${source_dir}' did not define required target '${QSD_TARGET}'")
    endif()
endfunction()
