include_guard(GLOBAL)

function(qiven_test_target_defaults target)
    if(ARGN)
        message(FATAL_ERROR "qiven_test_target_defaults: unexpected arguments: ${ARGN}")
    endif()
    qiven_target_defaults(${target} SCOPE PRIVATE FOLDER "Tests")
endfunction()

function(qiven_register_test)
    set(one_value_args NAME TARGET WORKING_DIRECTORY)
    set(multi_value_args ARGS)
    cmake_parse_arguments(QRT "" "${one_value_args}" "${multi_value_args}" ${ARGN})
    _qiven_require_clean_parse(QRT "qiven_register_test")

    if(NOT QRT_NAME OR NOT QRT_TARGET)
        message(FATAL_ERROR "qiven_register_test requires NAME and TARGET")
    endif()
    if(NOT TARGET ${QRT_TARGET})
        message(FATAL_ERROR "qiven_register_test: unknown target '${QRT_TARGET}'")
    endif()
    get_target_property(_imported_target ${QRT_TARGET} IMPORTED)
    if(_imported_target)
        message(FATAL_ERROR "qiven_register_test: imported test targets are not supported")
    endif()

    add_test(NAME ${QRT_NAME} COMMAND ${QRT_TARGET} ${QRT_ARGS})
    if(QRT_WORKING_DIRECTORY)
        set_tests_properties(${QRT_NAME} PROPERTIES WORKING_DIRECTORY "${QRT_WORKING_DIRECTORY}")
    endif()
endfunction()
